export const elementConstructorTagNameMap = new Map<new () => HTMLElement, string | string[]>([
    [HTMLAnchorElement, 'a'],
    // [HTMLUnknownElement, ['abbr', 'acronym', 'applet', 'basefont', 'big', 'center', 'dir', 'font', 'frame', 'frameset', 'menu', 'noframes', 'noscript', 'search', 'strike', 'tt']],
    // [HTMLElement, ['address', 'article', 'aside', 'b', 'bdi', 'bdo', 'cite', 'code', 'dd', 'dt', 'dfn', 'figcaption', 'figure', 'footer', 'header', 'hgroup', 'i', 'kbd', 'main', 'mark', 'nav', 'rp', 'rt', 'ruby', 's', 'samp', 'section', 'small', 'strong', 'sub', 'summary', 'sup', 'svg', 'u', 'var', 'wbr']],
    [HTMLAreaElement, 'area'],
    [HTMLAudioElement, 'audio'],
    [HTMLBaseElement, 'base'],
    // [HTMLQuoteElement, ['blockquote', 'q']],
    [HTMLQuoteElement, 'blockquote'],
    [HTMLBodyElement, 'body'],
    [HTMLBRElement, 'br'],
    [HTMLButtonElement, 'button'],
    [HTMLCanvasElement, 'canvas'],
    [HTMLTableCaptionElement, 'caption'],
    [HTMLDataElement, 'data'],
    [HTMLDataListElement, 'datalist'],
    [HTMLModElement, ['del', 'ins']],
    [HTMLDetailsElement, 'details'],
    [HTMLDialogElement, 'dialog'],
    [HTMLDivElement, 'div'],
    [HTMLDListElement, 'dl'],
    [HTMLEmbedElement, 'embed'],
    [HTMLFieldSetElement, 'fieldset'],
    [HTMLFormElement, 'form'],
    [HTMLHeadingElement, 'h1'],
    [HTMLHeadElement, 'head'],
    [HTMLHRElement, 'hr'],
    [HTMLHtmlElement, 'html'],
    [HTMLIFrameElement, 'iframe'],
    [HTMLImageElement, 'img'],
    [HTMLInputElement, 'input'],
    [HTMLLabelElement, 'label'],
    [HTMLLegendElement, 'legend'],
    [HTMLLIElement, 'li'],
    [HTMLLinkElement, 'link'],
    [HTMLMapElement, 'map'],
    [HTMLMetaElement, 'meta'],
    [HTMLMeterElement, 'meter'],
    [HTMLObjectElement, 'object'],
    [HTMLOListElement, 'ol'],
    [HTMLOptGroupElement, 'optgroup'],
    [HTMLOptionElement, 'option'],
    [HTMLOutputElement, 'output'],
    [HTMLParagraphElement, 'p'],
    [HTMLParamElement, 'param'],
    [HTMLPictureElement, 'picture'],
    [HTMLPreElement, 'pre'],
    [HTMLProgressElement, 'progress'],
    [HTMLScriptElement, 'script'],
    [HTMLSelectElement, 'select'],
    [HTMLSourceElement, 'source'],
    [HTMLSpanElement, 'span'],
    [HTMLStyleElement, 'style'],
    [HTMLTableElement, 'table'],
    [HTMLTableSectionElement, ['tbody', 'tfoot', 'thead']],
    [HTMLTableCellElement, ['td', 'th']],
    [HTMLTemplateElement, 'template'],
    [HTMLTextAreaElement, 'textarea'],
    [HTMLTimeElement, 'time'],
    [HTMLTitleElement, 'title'],
    [HTMLTableRowElement, 'tr'],
    [HTMLTrackElement, 'track'],
    [HTMLUListElement, 'ul'],
    [HTMLVideoElement, 'video'],
]);
